### ISSUE TITLE
codenames-service client for Rust

### ISSUE THREAD

**Issue by querqueq** [querqueq/untitled#1]
When running `rustForAPI (Proxy :: Proxy GameAPI)` in GHCI (Main module loaded) I get the following error:

```
<interactive>:13:1: error:
    • No instance for (servant-foreign-0.15:Servant.Foreign.Internal.HasForeignType
                         Servant.Rust.Rust Data.Text.Internal.Text Game.GameView)
        arising from a use of ‘rustForAPI’
    • In the expression: rustForAPI (Proxy :: Proxy GameAPI)
      In an equation for ‘it’: it = rustForAPI (Proxy :: Proxy GameAPI)
```

I'm using  https://github.com/dredozubov/servant-rust and apparently there isn't a representation for `Text` implemented. Although there seems to be an instance for it implemented in https://github.com/dredozubov/servant-rust/blob/master/src/Servant/Rust.hs

**Comment by liquidblock** [comment]
[servant-rust](https://github.com/dredozubov/servant-rust) only translates the API to a Rust client, which is not compatible with [yew](https://github.com/yewstack/yew).
Meaning that all data-types which are used in the API will not be translated.
I think, that the `Text` type in the error message is not the type which is translated, but rather the type which it is translated to. In that case `Text` is the type of the Rust-Code, since it outputs `Text`. (The second type argument of HasForeignType is named `ftype` and the method `typeFor` returns something of type `ftype` http://hackage.haskell.org/package/servant-foreign-0.15/docs/Servant-Foreign-Internal.html#t:HasForeignType)

**Comment by liquidblock** [comment]
What we need is something like `generateElmModuleWith`: https://hackage.haskell.org/package/servant-elm-0.7.1/docs/Servant-Elm-Internal-Generate.html#v:generateElmModuleWith
Which takes `[DefineElm]` and `Proxy api` as arguments, translating a list of type definitions and the API to elm code.
`DefineElm` is defined in the elm-bridge package: http://hackage.haskell.org/package/elm-bridge-0.5.2/docs/Elm-Module.html
This package uses template haskell to generate the elm equivalent.

**Comment by querqueq** [comment]
Not gonna generate a rust client with codenames-service for now.
Instead generating API reference with codenames-service for implementing a specific rust client.
https://github.com/querqueq/untitled/blob/master/codenames-service/API.md
